apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: detection-frontend
  template:
    metadata:
      labels:
        app: detection-frontend
    spec:
      containers:
      - image: alshu/detection-web:latest
        name: detection-frontend
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret

---
apiVersion: v1
kind: Service
metadata:
  name: detection-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: detection-frontend
  type: LoadBalancer
